[project]
name = "soil-analyzer"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "click",
    "pandas",
    "scikit-learn",
    "PyYAML",
]

[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"
